version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    environment:
      ENV_FILE: .env.test
    command: >
      bash -c "
      pytest -v tests/"
