version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    environment:
      ENV_FILE: .env.test
    volumes:
      - .:/app
    command: >
      bash -c "
      pytest -v tests/"
