version: "3"
services:
  oracle:
    image: gvenzl/oracle-xe:21.3.0-slim
    environment:
      - ORACLE_PASSWORD=oracle
      - APP_USER=pixelnote
      - APP_USER_PASSWORD=pixelnote
    ports:
      - 1521:1521
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus pixelnote/pixelnote@localhost/XEPDB1 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 10

  app:
    build:
      context: .
    depends_on:
      oracle:
        condition: service_healthy
    environment:
      DB_MODE: oracle
      DB_USER: pixelnote
      DB_PASSWORD: pixelnote
      DB_DSN: //oracle:1521/XEPDB1
    volumes:
      - ./app:/app/app
      - ./startup.sh:/app/startup.sh
      - ./app/db/init_oracle.py:/app/app/db/init_oracle.py
      - ./tests:/app/tests
      - ./requirements.txt:/app/requirements.txt
    command: sh -c "python app/db/init_oracle.py && pytest -v --maxfail=1 --disable-warnings tests"
