version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - oracle
  oracle:
    image: gvenzl/oracle-xe
    environment:
      ORACLE_PASSWORD: oracle
    ports:
      - "1521:1521"
    volumes:
      - ./oracle/init.sql:/container-entrypoint-initdb.d/init.sql
