name: CI (PixelNote)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # 手動実行用（ボタンでOracle CI起動）

jobs:
  test-sqlite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run SQLite tests
        env:
          DB_MODE: sqlite
        run: |
          pytest

  test-oracle:
    if: github.event_name == 'workflow_dispatch'   # 手動起動時のみ実行
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Start Oracle XE (gvenzl/oracle-xe)
        run: |
          docker run -d --name oracle-xe -e ORACLE_PASSWORD=oracle -p 1521:1521 gvenzl/oracle-xe:latest
          sleep 60  # 起動待ち
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install oracledb
      - name: Run Oracle tests
        env:
          DB_MODE: oracle
          DB_USER: system
          DB_PASSWORD: oracle
          DB_DSN: //localhost:1521/XEPDB1
        run: |
          pytest --oracle

